// Script seed du lieu cau hoi THPT cho QuizzGame.
// Moi mon trong SUBJECT_CATALOG: 5 cau de + 5 cau trung + 5 cau kho.
// Cau hoi theo style de thi THPT Quoc gia.
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface QuestionSeed {
  subject: string;
  chapter?: string;
  difficulty: number;
  question: string;
  options: [string, string, string, string];
  correctAnswer: number;
  explanation?: string;
  examYear?: number;
}

const questions: QuestionSeed[] = [
  // =========================================================================
  // TOAN - Toan hoc
  // =========================================================================

  // De (1)
  {
    subject: 'TOAN', difficulty: 1, chapter: 'Dai so',
    question: 'Tap nghiem cua bat phuong trinh 2x - 4 > 0 la:',
    options: ['x > 2', 'x < 2', 'x > -2', 'x < -2'],
    correctAnswer: 0,
    explanation: '2x - 4 > 0 <=> 2x > 4 <=> x > 2.',
  },
  {
    subject: 'TOAN', difficulty: 1, chapter: 'Hinh hoc',
    question: 'Dien tich hinh tron co ban kinh r = 5 cm la:',
    options: ['25π cm²', '10π cm²', '5π cm²', '50π cm²'],
    correctAnswer: 0,
    explanation: 'Dien tich hinh tron: S = πr² = π × 5² = 25π cm².',
  },
  {
    subject: 'TOAN', difficulty: 1, chapter: 'So hoc',
    question: 'Gia tri cua bieu thuc |−7| + |3| bang:',
    options: ['10', '4', '-4', '-10'],
    correctAnswer: 0,
    explanation: '|−7| = 7, |3| = 3. Tong = 7 + 3 = 10.',
  },
  {
    subject: 'TOAN', difficulty: 1, chapter: 'Dai so',
    question: 'Phuong trinh x² - 9 = 0 co nghiem la:',
    options: ['x = ±3', 'x = 3', 'x = -3', 'x = ±9'],
    correctAnswer: 0,
    explanation: 'x² = 9 => x = ±3.',
  },
  {
    subject: 'TOAN', difficulty: 1, chapter: 'Ham so',
    question: 'Ham so y = 2x + 3 la ham so:',
    options: ['Bac nhat (dong bien)', 'Bac nhat (nghich bien)', 'Bac hai', 'Khong xac dinh'],
    correctAnswer: 0,
    explanation: 'Ham y = ax + b la ham bac nhat. a = 2 > 0 nen ham dong bien.',
  },

  // Trung binh (2)
  {
    subject: 'TOAN', difficulty: 2, chapter: 'Luong giac',
    question: 'Gia tri cua sin²x + cos²x bang:',
    options: ['1', '0', '2', '-1'],
    correctAnswer: 0,
    explanation: 'Day la cong thuc luong giac co ban: sin²x + cos²x = 1.',
  },
  {
    subject: 'TOAN', difficulty: 2, chapter: 'Giai tich',
    question: 'Dao ham cua ham so y = x³ - 2x² + x la:',
    options: ['3x² - 4x + 1', '3x² - 4x', 'x³ - 4x', '3x - 4'],
    correctAnswer: 0,
    explanation: 'y\' = (x³)\' - (2x²)\' + (x)\' = 3x² - 4x + 1.',
  },
  {
    subject: 'TOAN', difficulty: 2, chapter: 'Hinh giai tich',
    question: 'Khoang cach tu goc toa do O(0;0) den diem A(3;4) la:',
    options: ['5', '7', '3', '4'],
    correctAnswer: 0,
    explanation: 'OA = √(3² + 4²) = √(9 + 16) = √25 = 5.',
  },
  {
    subject: 'TOAN', difficulty: 2, chapter: 'To hop',
    question: 'So cach chon 3 hoc sinh tu nhom 10 hoc sinh (khong phan biet thu tu) la:',
    options: ['120', '720', '360', '240'],
    correctAnswer: 0,
    explanation: 'C(10,3) = 10! / (3! × 7!) = 120.',
  },
  {
    subject: 'TOAN', difficulty: 2, chapter: 'Logarit',
    question: 'log₂(8) bang:',
    options: ['3', '4', '2', '8'],
    correctAnswer: 0,
    explanation: 'log₂(8) = log₂(2³) = 3.',
  },

  // Kho (3)
  {
    subject: 'TOAN', difficulty: 3, chapter: 'Tich phan',
    question: 'Tinh tich phan ∫₀¹ (2x + 1) dx:',
    options: ['2', '1', '3', '4'],
    correctAnswer: 0,
    explanation: '∫₀¹ (2x + 1)dx = [x² + x]₀¹ = (1 + 1) - 0 = 2.',
  },
  {
    subject: 'TOAN', difficulty: 3, chapter: 'So phuc',
    question: 'Modun cua so phuc z = 3 + 4i la:',
    options: ['5', '7', '1', '12'],
    correctAnswer: 0,
    explanation: '|z| = √(3² + 4²) = √(9 + 16) = √25 = 5.',
  },
  {
    subject: 'TOAN', difficulty: 3, chapter: 'Hinh hoc khong gian',
    question: 'The tich khoi lap phuong canh a = 3 cm la:',
    options: ['27 cm³', '9 cm³', '18 cm³', '54 cm³'],
    correctAnswer: 0,
    explanation: 'V = a³ = 3³ = 27 cm³.',
  },
  {
    subject: 'TOAN', difficulty: 3, chapter: 'Xac suat',
    question: 'Tung 1 dong tien xu 3 lan. Xac suat de ca 3 lan deu ra mat ngua la:',
    options: ['1/8', '1/4', '1/2', '3/8'],
    correctAnswer: 0,
    explanation: 'P = (1/2)³ = 1/8.',
  },
  {
    subject: 'TOAN', difficulty: 3, chapter: 'Day so',
    question: 'Tong 10 so hang dau cua cap so cong co a₁ = 1, cong sai d = 2 la:',
    options: ['100', '55', '90', '110'],
    correctAnswer: 0,
    explanation: 'S₁₀ = 10 × (2×1 + 9×2) / 2 = 10 × 20 / 2 = 100.',
  },

  // =========================================================================
  // VAN - Ngu van
  // =========================================================================

  { subject: 'VAN', difficulty: 1, chapter: 'Tieng Viet',
    question: 'Bien phap tu tu nao duoc dung trong cau: "Mat troi cua bap thi nhu mat troi cua chinh chu de"?',
    options: ['An du', 'Nhan hoa', 'Hoan du', 'Dieu phong'],
    correctAnswer: 0,
    explanation: '"Mat troi" duoc dung de chi nguoi con — day la bien phap an du.',
  },
  { subject: 'VAN', difficulty: 1, chapter: 'Tieng Viet',
    question: 'Tu "hoa no" trong cau "Hoa no mua xuan" thuoc loai:',
    options: ['Dong tu', 'Tinh tu', 'Danh tu', 'Pho tu'],
    correctAnswer: 0,
    explanation: '"No" chi hanh dong, bien doi trang thai — la dong tu.',
  },
  { subject: 'VAN', difficulty: 1, chapter: 'Van hoc',
    question: 'Tac pham "Truyen Kieu" duoc viet bang:',
    options: ['Chu Nom', 'Chu Han', 'Chu Quoc ngu', 'Chu Phap'],
    correctAnswer: 0,
    explanation: 'Truyen Kieu cua Nguyen Du duoc viet bang chu Nom theo the tho luc bat.',
  },
  { subject: 'VAN', difficulty: 1, chapter: 'Lam van',
    question: 'Doan van nghị luận can phai co:',
    options: ['Luan diem, luan cu, luan chung', 'Chi can luan diem', 'Chi can vi du', 'He de, than de, ket de'],
    correctAnswer: 0,
    explanation: 'Doan van nghi luan day du can co luan diem (y chinh), luan cu (ly le), luan chung (dan chung).',
  },
  { subject: 'VAN', difficulty: 1, chapter: 'Van hoc',
    question: 'The tho "luc bat" co so chu tren moi dong la:',
    options: ['6 va 8', '7 va 7', '5 va 7', '8 va 8'],
    correctAnswer: 0,
    explanation: 'The tho luc bat: dong chan 6 chu, dong le 8 chu, xen ke nhau.',
  },
  { subject: 'VAN', difficulty: 2, chapter: 'Van hoc',
    question: 'Tac pham "Tat den" cua Ngo Tat To phe phan hinh tuong nao sau day?',
    options: ['Bon cuong hao ac ba thoi truoc Cach mang', 'Thuc dan Phap', 'Bon dia chu phong kien', 'Chinh quyen tay sai'],
    correctAnswer: 0,
    explanation: 'Tat den phe phan cai xa hoi muc nat, trong do tiep diem la bon cuong hao ac ba ap buc nong dan.',
  },
  { subject: 'VAN', difficulty: 2, chapter: 'Van hoc',
    question: 'Hinh tuong "song" trong bai tho "Song" cua Xuan Quynh bieu trung cho:',
    options: ['Tinh yeu cua nguoi phu nu', 'Mua thu', 'Que huong', 'Dat nuoc'],
    correctAnswer: 0,
    explanation: 'Hinh tuong song la bien the cua cai toi tru tinh, bieu trung cho tam hon nguoi con gai dang yeu.',
  },
  { subject: 'VAN', difficulty: 2, chapter: 'Tieng Viet',
    question: 'Phong cach ngon ngu nao duoc dung trong van ban bao chi?',
    options: ['Bao chi', 'Nghe thuat', 'Khoa hoc', 'Hanh chinh'],
    correctAnswer: 0,
    explanation: 'Van ban bao chi su dung phong cach ngon ngu bao chi, voi dac trung: thong tin, chinh xac, ngan gon.',
  },
  { subject: 'VAN', difficulty: 2, chapter: 'Lam van',
    question: 'Mo bai cua bai van nghi luan xa hoi thuong:',
    options: ['Gioi thieu van de can ban luan', 'Trinh bay luan diem chinh', 'Neu dan chung cu the', 'Ket luan van de'],
    correctAnswer: 0,
    explanation: 'Mo bai xac dinh de tai, gioi thieu van de can ban luan de dinh huong cho bai viet.',
  },
  { subject: 'VAN', difficulty: 2, chapter: 'Van hoc',
    question: 'Nhan vat Chu Dong Tu trong truyen dan gian Viet Nam the hien:',
    options: ['Uoc mo ve tinh yeu va hanh phuc doi doi', 'Khat vong chien thang ke thu', 'Tinh than lao dong san xuat', 'Long biet on to tien'],
    correctAnswer: 0,
    explanation: 'Truyen Chu Dong Tu - Tien Dung the hien uoc mo ve tinh yeu chu dong, vuot qua ranh gioi giau ngheo.',
  },
  { subject: 'VAN', difficulty: 3, chapter: 'Van hoc',
    question: 'Chi tiet "chiec bong den" trong truyen ngan "Hai dua tre" cua Thach Lam bieu trung cho:',
    options: ['Tia sang nho noi, khat vong ve cuoc song tot dep', 'Bong toi cua xa hoi cu', 'Su ngheo doi', 'Hanh phuc gia dinh'],
    correctAnswer: 0,
    explanation: 'Bong den "leo let" tren pho huyen nho bieu trung cho niem tin nho nhen, khat vong ve cuoc doi khac — nguoc voi bong toi menh mong bao quanh.',
  },
  { subject: 'VAN', difficulty: 3, chapter: 'Van hoc',
    question: 'Trong "Chinh phu ngam khuc", tiet tau "song that luc bat" tao hieu qua gi?',
    options: ['Dien ta noi buon dan dang, tu tu', 'Tao cam giac vui tuoi', 'Bieu dat su phan khich', 'Mieu ta thien nhien'],
    correctAnswer: 0,
    explanation: 'Nhip dieu song that luc bat voi cac dong dai ngan xen ke tao cam giac day von, noi dau triem mien cua nguoi chinh phu.',
  },
  { subject: 'VAN', difficulty: 3, chapter: 'Lam van',
    question: 'Luan diem chinh trong bai nghi luan can duoc:',
    options: ['The hien ro rang, nhat quan, co chieu sau tu tuong', 'Chi can ngan gon, ro rang', 'Neu duoc nhieu y kien trai chieu', 'Trich dan nhieu tu lieu'],
    correctAnswer: 0,
    explanation: 'Luan diem chinh phai nhat quan xuyen suot, ro rang ve mat noi dung va co chieu sau tu tuong de thuyet phuc nguoi doc.',
  },
  { subject: 'VAN', difficulty: 3, chapter: 'Van hoc',
    question: 'Ket thuc truyen ngan "Vi hanh" cua Ho Chi Minh the hien:',
    options: ['Su vo ly, bat cong cua che do thuc dan', 'Niem vui cua nguoi dan Phap', 'Long biet on voi toan quoc', 'Su hung vu cua chuyen tham'],
    correctAnswer: 0,
    explanation: 'Cai ket bieu lo su vo ly cua "su vu vi hanh" trong con mat nguoi Phap, qua do to cao tinh chat bo bien cua bon thuc dan.',
  },
  { subject: 'VAN', difficulty: 3, chapter: 'Van hoc',
    question: 'Bai tho "Tay Tien" cua Quang Dung duoc viet theo phong cach:',
    options: ['Cam hung lang man cam hung yeu nuoc', 'Hien thuc phe phan', 'Phuong Tay hien dai', 'Co dien chuong trinh'],
    correctAnswer: 0,
    explanation: 'Tay Tien ket hop cam hung lang man (ve dep hung vi cua thien nhien, su bi trang cua nguoi linh) va cam hung yeu nuoc (long trung thanh, hai hung).',
  },

  // =========================================================================
  // ANH - Tieng Anh
  // =========================================================================

  { subject: 'ANH', difficulty: 1, chapter: 'Grammar',
    question: 'Choose the correct form: "She _____ to school every day."',
    options: ['goes', 'go', 'going', 'gone'],
    correctAnswer: 0,
    explanation: 'Subject "She" (he/she/it) requires the verb with -s/-es in simple present: "goes".',
  },
  { subject: 'ANH', difficulty: 1, chapter: 'Vocabulary',
    question: 'What is the opposite of "happy"?',
    options: ['sad', 'angry', 'tired', 'bored'],
    correctAnswer: 0,
    explanation: '"Sad" is the direct opposite (antonym) of "happy".',
  },
  { subject: 'ANH', difficulty: 1, chapter: 'Grammar',
    question: 'Fill in: "There _____ many students in the classroom."',
    options: ['are', 'is', 'was', 'be'],
    correctAnswer: 0,
    explanation: '"There are" is used with plural countable nouns. "students" is plural → "are".',
  },
  { subject: 'ANH', difficulty: 1, chapter: 'Reading',
    question: 'The word "enormous" means:',
    options: ['very large', 'very small', 'very fast', 'very old'],
    correctAnswer: 0,
    explanation: '"Enormous" means extremely large in size or quantity.',
  },
  { subject: 'ANH', difficulty: 1, chapter: 'Grammar',
    question: 'Which sentence is grammatically correct?',
    options: ['I have lived here for 3 years.', 'I live here since 3 years.', 'I am living here since 3 years.', 'I lived here for 3 years ago.'],
    correctAnswer: 0,
    explanation: 'Present Perfect with "for" is used for a period of time that continues to the present.',
  },
  { subject: 'ANH', difficulty: 2, chapter: 'Grammar',
    question: 'Choose the correct passive form: "The teacher _____ the test yesterday."',
    options: ['was corrected by', 'corrected', 'has corrected', 'is correcting'],
    correctAnswer: 0,
    explanation: 'Passive voice in past simple: was/were + past participle. "was corrected by".',
  },
  { subject: 'ANH', difficulty: 2, chapter: 'Grammar',
    question: 'If I _____ rich, I would travel the world.',
    options: ['were', 'am', 'was', 'will be'],
    correctAnswer: 0,
    explanation: 'Second conditional (hypothetical present/future): If + past simple, would + base verb. Use "were" for all subjects in formal/standard English.',
  },
  { subject: 'ANH', difficulty: 2, chapter: 'Vocabulary',
    question: 'The word "perseverance" means:',
    options: ['continued effort despite difficulties', 'sudden change', 'quick success', 'lack of interest'],
    correctAnswer: 0,
    explanation: '"Perseverance" refers to persistence and determination in doing something despite difficulty.',
  },
  { subject: 'ANH', difficulty: 2, chapter: 'Grammar',
    question: 'She suggested _____ to the cinema.',
    options: ['going', 'to go', 'go', 'went'],
    correctAnswer: 0,
    explanation: '"Suggest" is followed by a gerund (verb + -ing), not an infinitive.',
  },
  { subject: 'ANH', difficulty: 2, chapter: 'Reading',
    question: '"The more you practice, the _____ you become."',
    options: ['better', 'best', 'good', 'well'],
    correctAnswer: 0,
    explanation: 'The comparative structure: "the + comparative, the + comparative". "better" is the comparative form of "good".',
  },
  { subject: 'ANH', difficulty: 3, chapter: 'Grammar',
    question: 'Choose the sentence that uses the subjunctive mood correctly:',
    options: ['It is important that he be present.', 'It is important that he is present.', 'It is important that he was present.', 'It is important for he to be present.'],
    correctAnswer: 0,
    explanation: 'The subjunctive mood uses the base form of the verb (be, not is/was) after expressions like "it is important that...".',
  },
  { subject: 'ANH', difficulty: 3, chapter: 'Vocabulary',
    question: '"Ubiquitous" most nearly means:',
    options: ['present everywhere', 'completely absent', 'extremely rare', 'highly dangerous'],
    correctAnswer: 0,
    explanation: '"Ubiquitous" describes something that appears to be present everywhere at the same time.',
  },
  { subject: 'ANH', difficulty: 3, chapter: 'Grammar',
    question: 'Which sentence contains a dangling modifier?',
    options: ['Running down the street, the rain soaked him.', 'He was soaked by the rain while running.', 'The rain soaked him as he ran.', 'Running in the rain, he got soaked.'],
    correctAnswer: 0,
    explanation: 'In "Running down the street, the rain soaked him," the participial phrase "running down the street" incorrectly modifies "rain" instead of "him".',
  },
  { subject: 'ANH', difficulty: 3, chapter: 'Reading',
    question: 'The author\'s primary purpose in a persuasive essay is to:',
    options: ['convince the reader to adopt a particular viewpoint', 'describe events chronologically', 'explain how something works', 'entertain the reader with a story'],
    correctAnswer: 0,
    explanation: 'A persuasive essay aims to persuade or convince the reader to accept a specific argument or take a particular action.',
  },
  { subject: 'ANH', difficulty: 3, chapter: 'Grammar',
    question: 'Which option correctly uses "whom"?',
    options: ['The man whom I met yesterday was kind.', 'The man who I met yesterday was kind.', 'Whom is coming to the party?', 'Whom told you that?'],
    correctAnswer: 0,
    explanation: '"Whom" is used as an object pronoun. In "whom I met," "whom" is the object of "met". The others use "whom" incorrectly as a subject.',
  },

  // =========================================================================
  // LY - Vat ly
  // =========================================================================

  { subject: 'LY', difficulty: 1, chapter: 'Co hoc',
    question: 'Cong thuc tinh van toc trong chuyen dong deu la:',
    options: ['v = s/t', 'v = s × t', 'v = t/s', 'v = s - t'],
    correctAnswer: 0,
    explanation: 'Trong chuyen dong deu, van toc v bang quang duong s chia cho thoi gian t: v = s/t.',
  },
  { subject: 'LY', difficulty: 1, chapter: 'Dien hoc',
    question: 'Don vi do cua dien tro la:',
    options: ['Ohm (Ω)', 'Ampe (A)', 'Vôn (V)', 'Watt (W)'],
    correctAnswer: 0,
    explanation: 'Dien tro duoc do bang don vi Ohm (Ω), theo dinh luat Ohm: R = U/I.',
  },
  { subject: 'LY', difficulty: 1, chapter: 'Nhiet hoc',
    question: 'Nuoc soi o nhiet do bao nhieu o ap suat khi quyen binh thuong?',
    options: ['100°C', '90°C', '110°C', '80°C'],
    correctAnswer: 0,
    explanation: 'O ap suat khi quyen binh thuong (1 atm), nuoc soi o 100°C.',
  },
  { subject: 'LY', difficulty: 1, chapter: 'Quang hoc',
    question: 'Anh sang truyen di theo:',
    options: ['Duong thang', 'Duong cong', 'Duong tron', 'Duong xoan oc'],
    correctAnswer: 0,
    explanation: 'Anh sang truyen theo duong thang trong moi truong dong nhat.',
  },
  { subject: 'LY', difficulty: 1, chapter: 'Co hoc',
    question: 'Dinh luat I Newton phat bieu rang vat bao gio cung:',
    options: ['Giu nguyen trang thai neu tong luc bang 0', 'Chuyen dong nhanh khi bi tac dong', 'Dung lai khi khong co luc', 'Chuyen dong nhanh dan'],
    correctAnswer: 0,
    explanation: 'Dinh luat quan tinh: neu tong hop luc tac dong len vat bang 0, vat giu nguyen trang thai (dung yen hoac chuyen dong thang deu).',
  },
  { subject: 'LY', difficulty: 2, chapter: 'Dien hoc',
    question: 'Theo dinh luat Ohm, neu tang hieu dien the gap doi trong khi giu nguyen dien tro thi cuong do dong dien se:',
    options: ['Tang gap doi', 'Giam di mot nua', 'Khong doi', 'Tang gap 4 lan'],
    correctAnswer: 0,
    explanation: 'Dinh luat Ohm: I = U/R. Neu U tang x2, R giu nguyen => I tang x2.',
  },
  { subject: 'LY', difficulty: 2, chapter: 'Co hoc',
    question: 'Cong thuc tinh dong nang la:',
    options: ['Wd = ½mv²', 'Wd = mgh', 'Wd = mv', 'Wd = mv²'],
    correctAnswer: 0,
    explanation: 'Dong nang: Wd = ½mv², voi m la khoi luong, v la van toc.',
  },
  { subject: 'LY', difficulty: 2, chapter: 'Song',
    question: 'Van toc truyen am trong khong khi o 20°C xap xi:',
    options: ['343 m/s', '300 m/s', '1500 m/s', '100 m/s'],
    correctAnswer: 0,
    explanation: 'O nhiet do phong (20°C), van toc am trong khong khi xap xi 343 m/s.',
  },
  { subject: 'LY', difficulty: 2, chapter: 'Nhiet hoc',
    question: 'Hieu ung nha kinh xay ra chu yeu do:',
    options: ['Khi CO₂ giu nhiet tu mat dat', 'Mat troi dot nong truc tiep', 'May che phu mat dat', 'Cay xanh quang hop'],
    correctAnswer: 0,
    explanation: 'Hieu ung nha kinh: cac khi nhu CO₂, CH₄ hap thu va tai ban xa buc xa nhiet (tia hong ngoai) tu mat dat, lam tang nhiet do.',
  },
  { subject: 'LY', difficulty: 2, chapter: 'Quang hoc',
    question: 'Goc khuc xa cua anh sang khi truyen tu nuoc vao khong khi so voi goc toi:',
    options: ['Lon hon', 'Nho hon', 'Bang', 'Khong xac dinh'],
    correctAnswer: 0,
    explanation: 'Nuoc co chiet suat lon hon khong khi. Khi anh sang di tu moi truong chiet suat cao sang thap (nuoc -> kk), goc khuc xa > goc toi.',
  },
  { subject: 'LY', difficulty: 3, chapter: 'Vat ly hat nhan',
    question: 'Trong phan ung phan ra hat nhan, nang luong giai phong la do:',
    options: ['Do hut khoi (M_truoc > M_sau)', 'Tang nhiet do', 'Chuyen dong hat nhan', 'Tu truong'],
    correctAnswer: 0,
    explanation: 'E = Δm × c², trong do Δm = M_truoc - M_sau. Do hut khoi chuyen hoa thanh nang luong theo Einstein.',
  },
  { subject: 'LY', difficulty: 3, chapter: 'Dien tu',
    question: 'Mach dao dong LC co tan so cong huong f = 1/(2π√LC). Neu tang dien dung C len 4 lan, tan so se:',
    options: ['Giam di 2 lan', 'Tang len 2 lan', 'Giam di 4 lan', 'Khong doi'],
    correctAnswer: 0,
    explanation: 'f = 1/(2π√LC). Neu C tang 4 lan => √LC tang 2 lan => f giam 2 lan.',
  },
  { subject: 'LY', difficulty: 3, chapter: 'Co hoc luong tu',
    question: 'Nguyen ly bat dinh Heisenberg phat bieu rang:',
    options: ['Khong the xac dinh dong thoi vi tri va xung luong chinh xac', 'Electron chuyen dong theo quy dao xac dinh', 'Nang luong luon bao toan', 'Hat nhan ben vung'],
    correctAnswer: 0,
    explanation: 'Nguyen ly bat dinh Heisenberg: Δx × Δp ≥ ħ/2 — khong the dong thoi biet chinh xac vi tri va dong luong cua hat.',
  },
  { subject: 'LY', difficulty: 3, chapter: 'Song dien tu',
    question: 'Trong song dien tu, vec to E va B:',
    options: ['Vuong goc nhau va vuong goc voi phuong truyen', 'Song song nhau', 'E theo phuong truyen, B vuong goc', 'B theo phuong truyen, E vuong goc'],
    correctAnswer: 0,
    explanation: 'Song dien tu: vec to E, B luon vuong goc nhau va ca hai vuong goc voi phuong truyen song.',
  },
  { subject: 'LY', difficulty: 3, chapter: 'Vat ly hat nhan',
    question: 'Chu ky ban ra cua C-14 xap xi 5730 nam. Sau 11460 nam, luong C-14 con lai la:',
    options: ['25%', '50%', '12.5%', '75%'],
    correctAnswer: 0,
    explanation: '11460 = 2 × 5730 => 2 chu ky ban ra. Con lai: (1/2)² = 1/4 = 25%.',
  },

  // =========================================================================
  // HOA - Hoa hoc
  // =========================================================================

  { subject: 'HOA', difficulty: 1, chapter: 'Dai cuong',
    question: 'Nguyen tu khoi cua nguyen to C (Carbon) la:',
    options: ['12', '14', '6', '16'],
    correctAnswer: 0,
    explanation: 'Carbon (C) co so hieu nguyen tu Z = 6, nguyen tu khoi A = 12.',
  },
  { subject: 'HOA', difficulty: 1, chapter: 'Dai cuong',
    question: 'Cong thuc hoa hoc cua nuoc la:',
    options: ['H₂O', 'HO', 'H₂O₂', 'OH'],
    correctAnswer: 0,
    explanation: 'Nuoc gom 2 nguyen tu Hydro va 1 nguyen tu Oxy: H₂O.',
  },
  { subject: 'HOA', difficulty: 1, chapter: 'Phi kim',
    question: 'Nguyen to nao luon co hoa tri I trong hop chat?',
    options: ['Flo (F)', 'Oxy (O)', 'Clo (Cl)', 'Nito (N)'],
    correctAnswer: 0,
    explanation: 'Flo la phi kim manh nhat, chi co hoa tri I (-1) trong moi hop chat.',
  },
  { subject: 'HOA', difficulty: 1, chapter: 'Dung dich',
    question: 'Dung dich axit co pH:',
    options: ['< 7', '> 7', '= 7', '= 14'],
    correctAnswer: 0,
    explanation: 'Dung dich axit co [H⁺] > 10⁻⁷ M, tuong duong pH < 7.',
  },
  { subject: 'HOA', difficulty: 1, chapter: 'Phan ung hoa hoc',
    question: 'Phan ung "Fe + 2HCl → FeCl₂ + H₂↑" la loai phan ung:',
    options: ['The cua kim loai', 'Trung hoa', 'Nhiet phan', 'Tong hop'],
    correctAnswer: 0,
    explanation: 'Fe (kim loai) the cho H trong HCl giai phong khi H₂ — day la phan ung the.',
  },
  { subject: 'HOA', difficulty: 2, chapter: 'Dai cuong',
    question: 'Nguyen tu co 17 proton. Nguyen to nay thuoc chu ki va nhom nao trong bang tuan hoan?',
    options: ['Chu ki 3, nhom VIIA', 'Chu ki 2, nhom IA', 'Chu ki 4, nhom IA', 'Chu ki 3, nhom IA'],
    correctAnswer: 0,
    explanation: 'Z = 17 (Clo). Cau hinh e: 2,8,7. Lop 3 => chu ki 3. 7 electron lop ngoai cung => nhom VIIA.',
  },
  { subject: 'HOA', difficulty: 2, chapter: 'Huu co',
    question: 'Chat huu co co cong thuc phan tu C₂H₄ co ten goi la:',
    options: ['Etilen', 'Etan', 'Metan', 'Axetilen'],
    correctAnswer: 0,
    explanation: 'C₂H₄ = CH₂=CH₂ la etilen (eten), hydrocarbon khong no co 1 lien ket doi.',
  },
  { subject: 'HOA', difficulty: 2, chapter: 'Kim loai',
    question: 'Khi nhung thanh sat vao dung dich CuSO₄, phan ung xay ra la:',
    options: ['Fe + CuSO₄ → FeSO₄ + Cu', 'Khong co phan ung', 'Fe bi hoa tan hoan toan', 'Cu bi hoa tan'],
    correctAnswer: 0,
    explanation: 'Fe hoat dong hon Cu => Fe co the day Cu ra khoi dung dich muoi. Fe + CuSO₄ → FeSO₄ + Cu↓.',
  },
  { subject: 'HOA', difficulty: 2, chapter: 'Dung dich',
    question: 'Chuan do 20 mL dung dich NaOH 0.1M voi dung dich HCl. The tich HCl 0.1M can dung la:',
    options: ['20 mL', '10 mL', '40 mL', '5 mL'],
    correctAnswer: 0,
    explanation: 'n(NaOH) = 0.02 × 0.1 = 0.002 mol. NaOH + HCl → NaCl + H₂O. n(HCl) = n(NaOH) = 0.002 mol. V(HCl) = 0.002/0.1 = 0.02 L = 20 mL.',
  },
  { subject: 'HOA', difficulty: 2, chapter: 'Phi kim',
    question: 'Khi Cl₂ tac dung voi NaOH loang o nhiet do thuong, san pham tao thanh la:',
    options: ['NaCl + NaClO + H₂O', 'NaCl + H₂O', 'NaClO₃ + HCl', 'NaCl + Cl₂O'],
    correctAnswer: 0,
    explanation: 'Cl₂ + 2NaOH (lanh) → NaCl + NaClO + H₂O. Day la phan ung tu oxi hoa - khu.',
  },
  { subject: 'HOA', difficulty: 3, chapter: 'Dai cuong',
    question: 'Toc do phan ung hoa hoc thay doi the nao khi tang nhiet do them 10°C (theo quy tac Van\'t Hoff)?',
    options: ['Tang gap 2-4 lan', 'Giam di 2 lan', 'Khong thay doi', 'Tang them 10 lan'],
    correctAnswer: 0,
    explanation: 'Theo quy tac Van\'t Hoff: khi tang 10°C, toc do phan ung tang len 2-4 lan (he so nhiet gamma = 2-4).',
  },
  { subject: 'HOA', difficulty: 3, chapter: 'Huu co',
    question: 'Anilin (C₆H₅NH₂) co tinh chat nao sau day?',
    options: ['Baz yeu, tac dung voi axit manh', 'Axit yeu', 'Baz manh', 'Trung tinh hoan toan'],
    correctAnswer: 0,
    explanation: 'Anilin la amin thom, co tinh baz nhung yeu hon NH₃ vi nhan benzen hut electron lam giam mat do e tren N. Tac dung voi HCl: C₆H₅NH₂ + HCl → C₆H₅NH₃Cl.',
  },
  { subject: 'HOA', difficulty: 3, chapter: 'Dien hoa',
    question: 'Trong qua trinh dien phan dung dich NaCl, o catot xay ra phan ung:',
    options: ['2H₂O + 2e⁻ → H₂↑ + 2OH⁻', 'Na⁺ + e⁻ → Na', '2Cl⁻ → Cl₂↑ + 2e⁻', 'H₂O → H⁺ + OH⁻'],
    correctAnswer: 0,
    explanation: 'Trong dung dich, ion Na⁺ kho bi khu hon H₂O. O catot: 2H₂O + 2e⁻ → H₂↑ + 2OH⁻.',
  },
  { subject: 'HOA', difficulty: 3, chapter: 'Phan tich',
    question: 'De xac dinh glucose trong nuoc tieu benh nhan tieu duong, nguoi ta thuong dung:',
    options: ['Phan ung trang guong (dung dich Tollens)', 'Quy tim', 'Phan ung voi NaOH', 'Phan ung voi HCl'],
    correctAnswer: 0,
    explanation: 'Glucose co nhom -CHO nen co the khu Ag⁺ trong dung dich Tollens (AgNO₃/NH₃) tao bac trang bang tren thanh binh (phan ung trang guong).',
  },
  { subject: 'HOA', difficulty: 3, chapter: 'Huu co',
    question: 'Xeten (CH₂=C=O) phan ung voi H₂O tao ra:',
    options: ['Axit axetic (CH₃COOH)', 'Axeton', 'Etilen', 'Andehit axetic'],
    correctAnswer: 0,
    explanation: 'Xeten cong nuoc theo co che: CH₂=C=O + H₂O → CH₃COOH (axit axetic).',
  },

  // =========================================================================
  // SINH - Sinh hoc
  // =========================================================================

  { subject: 'SINH', difficulty: 1, chapter: 'Te bao',
    question: 'Trung tam nang luong cua te bao la:',
    options: ['Ti the (Mitochondria)', 'Nhan te bao', 'Ribosome', 'Lysosome'],
    correctAnswer: 0,
    explanation: 'Ti the tong hop ATP qua qua trinh ho hap te bao — duoc goi la "nha may nang luong" cua te bao.',
  },
  { subject: 'SINH', difficulty: 1, chapter: 'Di truyen',
    question: 'ADN lam khuon tong hop ARN la qua trinh:',
    options: ['Phien ma', 'Dich ma', 'Nhan doi', 'Bien di'],
    correctAnswer: 0,
    explanation: 'Phien ma (Transcription): ADN lam khuon -> tong hop mARN. Dich ma (Translation): mARN lam khuon -> tong hop protein.',
  },
  { subject: 'SINH', difficulty: 1, chapter: 'Thuc vat',
    question: 'Qua trinh quang hop o thuc vat xay ra o:',
    options: ['Luc lap (Chloroplast)', 'Ti the', 'Nhan te bao', 'Ribosome'],
    correctAnswer: 0,
    explanation: 'Quang hop xay ra o luc lap, noi co chua sac to quang hop (diet luc, carotenoid).',
  },
  { subject: 'SINH', difficulty: 1, chapter: 'Vi sinh vat',
    question: 'Vi sinh vat nao co cau tao don gian nhat, khong co mang nhan?',
    options: ['Vi khuan (Bacteria)', 'Nam men', 'Vi rut', 'Dong vat nguyen sinh'],
    correctAnswer: 0,
    explanation: 'Vi khuan la sinh vat nhan so (Prokaryote) — khong co mang nhan bao boc vat chat di truyen.',
  },
  { subject: 'SINH', difficulty: 1, chapter: 'Di truyen',
    question: 'Nguyen tac bo sung trong ADN la:',
    options: ['A-T va G-X', 'A-U va G-X', 'A-G va T-X', 'A-X va G-T'],
    correctAnswer: 0,
    explanation: 'Trong ADN: Adenin (A) lien ket voi Timin (T) bang 2 lien ket H; Guanin (G) lien ket voi Xitozin (X) bang 3 lien ket H.',
  },
  { subject: 'SINH', difficulty: 2, chapter: 'Di truyen',
    question: 'Quy luat phan li doc lap cua Mendel ap dung khi:',
    options: ['Cac gen nam tren nhung NST khac nhau', 'Cac gen nam tren cung NST', 'Gen bi bien di', 'Tuong tac gen'],
    correctAnswer: 0,
    explanation: 'Quy luat phan li doc lap: cac cap gen nam tren cac cap NST tuong dong khac nhau phan li doc lap trong giam phan.',
  },
  { subject: 'SINH', difficulty: 2, chapter: 'Tien hoa',
    question: 'Theo Darwin, dong luc cua qua trinh tien hoa la:',
    options: ['Chon loc tu nhien', 'Bien di to hop', 'Di cu', 'Bien di gen'],
    correctAnswer: 0,
    explanation: 'Darwin: bien di va chon loc tu nhien la dong luc chu yeu. Bien di tao da dang, chon loc tu nhien giu lai bien di co loi.',
  },
  { subject: 'SINH', difficulty: 2, chapter: 'Sinh thai hoc',
    question: 'Quan he gi giup ca hai loai deu co loi trong quan he giua ong va hoa?',
    options: ['Cong sinh (Mutualism)', 'Canh tranh', 'Ky sinh', 'Hat sinh'],
    correctAnswer: 0,
    explanation: 'Ong lay phan hoa (thuc an) — hoa duoc thu phan. Ca hai deu co loi: cong sinh.',
  },
  { subject: 'SINH', difficulty: 2, chapter: 'Phan tu',
    question: 'Enzyme nao su dung trong phan ung chuoi polymerase (PCR)?',
    options: ['Taq polymerase', 'Ligase', 'Restrictase', 'Helicase'],
    correctAnswer: 0,
    explanation: 'PCR dung Taq polymerase — ADN polymerase chiu nhiet lay tu vi khuan Thermus aquaticus song o suoi nuoc nong.',
  },
  { subject: 'SINH', difficulty: 2, chapter: 'Di truyen',
    question: 'Dot bien gen la:',
    options: ['Bien doi trong cau truc gen (them, mat, thay the nucleotide)', 'Bien doi so luong NST', 'Mat mot doan NST', 'Dao doan NST'],
    correctAnswer: 0,
    explanation: 'Dot bien gen la bien doi trong trinh tu nucleotide cua gen: them, mat, thay the 1 hoac vai cap nucleotide.',
  },
  { subject: 'SINH', difficulty: 3, chapter: 'Di truyen',
    question: 'Trong dieu hoa hoat dong gen o sinh vat nhan so (mo hinh lac operon), protein uc che (repressor):',
    options: ['Gan vao vung operator khi khong co chất cam ung, uc che phien ma', 'Kich thich phien ma', 'Phan huy mARN', 'Bien doi cau truc gen'],
    correctAnswer: 0,
    explanation: 'Khi khong co lactose (chat cam ung), repressor gan vao operator -> ngan RNA polymerase -> uc che tong hop enzyme cho len. Khi co lactose, lactose gan vao repressor -> repressor tach khoi operator -> phien ma xay ra.',
  },
  { subject: 'SINH', difficulty: 3, chapter: 'Tien hoa',
    question: 'Hieu ung co sang la gi?',
    options: ['Bien dong ngau nhien tan so alen do quan the nho bi tach bi nguoi co lap', 'Chon loc tu nhien tac dong', 'Nhap cu tu quan the khac', 'Dot bien lam tang tan so alen'],
    correctAnswer: 0,
    explanation: 'Hieu ung co sang (Founder Effect): mot nhom nho ca the tach khoi quan the lon, mang theo tan so alen khong dai dien — quan the moi phat trien tu nhom nho nay.',
  },
  { subject: 'SINH', difficulty: 3, chapter: 'Cong nghe sinh hoc',
    question: 'Ky thuat CRISPR-Cas9 duoc su dung de:',
    options: ['Chinh sua gen chinh xac tai vi tri chi dinh', 'Nhan ban ADN', 'Tong hop protein', 'Phan tich trinh tu ADN'],
    correctAnswer: 0,
    explanation: 'CRISPR-Cas9 la he thong chinh sua gen chinh xac: RNA dan duong (gRNA) huong protein Cas9 cat ADN tai vi tri mong muon de them, xoa hoac thay the gen.',
  },
  { subject: 'SINH', difficulty: 3, chapter: 'Sinh thai',
    question: 'Nguyen nhan chinh dan den su giam sat tuyen sinh hoc trong nhung thap nien qua?',
    options: ['Pha huy va mat noi o sinh vat', 'Khai thac bui', 'O nhiem nuoc', 'Bien doi khi hau'],
    correctAnswer: 0,
    explanation: 'Pha huy va mat noi song (habitat loss) do chuyen doi su dung dat, pha rung, do thi hoa la nguyen nhan hang dau gay suy giam da dang sinh hoc toan cau.',
  },
  { subject: 'SINH', difficulty: 3, chapter: 'Phan tu',
    question: 'mARN co vai tro nao trong tong hop protein?',
    options: ['Lam khuon cho ribosome dich ma thanh trinh tu axit amin', 'Lam khuon tong hop ADN', 'Van chuyen axit amin', 'Cau truc ribosome'],
    correctAnswer: 0,
    explanation: 'mARN (messenger RNA) la ban sao thong tin tu ADN, lam khuon de ribosome doc va dich sang trinh tu axit amin cua protein.',
  },

  // =========================================================================
  // SU - Lich su
  // =========================================================================

  { subject: 'SU', difficulty: 1, chapter: 'Lich su Viet Nam',
    question: 'Cuoc Khang chien chong Phap cua nhan dan Viet Nam ket thuc bang:',
    options: ['Chien thang Dien Bien Phu (1954)', 'Hiep dinh Geneve', 'Cach mang thang 8', 'Tong tien cong 1975'],
    correctAnswer: 0,
    explanation: 'Chien thang Dien Bien Phu ngay 7/5/1954 ket thuc cuoc khang chien chong Phap, dan den viec ky ket Hiep dinh Geneve.',
  },
  { subject: 'SU', difficulty: 1, chapter: 'Lich su the gioi',
    question: 'Chien tranh The gioi II ket thuc nam:',
    options: ['1945', '1944', '1946', '1939'],
    correctAnswer: 0,
    explanation: 'Chien tranh the gioi II ket thuc nam 1945: Duc dau hang 5/1945, Nhat dau hang 9/1945.',
  },
  { subject: 'SU', difficulty: 1, chapter: 'Lich su Viet Nam',
    question: 'Cach mang Thang Tam 1945 thanh cong khi nao?',
    options: ['Ngay 19/8/1945', 'Ngay 2/9/1945', 'Ngay 22/12/1944', 'Ngay 1/5/1945'],
    correctAnswer: 0,
    explanation: 'Ngay 19/8/1945 la ngay cuoc khoi nghia gianh chinh quyen thanh cong o Ha Noi, mo dau toan thang cua Cach mang Thang Tam.',
  },
  { subject: 'SU', difficulty: 1, chapter: 'Lich su the gioi',
    question: 'Lien Xo (USSR) tan ra vao nam:',
    options: ['1991', '1985', '1989', '2000'],
    correctAnswer: 0,
    explanation: 'Lien Xo chinh thuc tan ra ngay 25/12/1991 khi Gorbachev tu chuc, phan thanh 15 nuoc doc lap.',
  },
  { subject: 'SU', difficulty: 1, chapter: 'Lich su Viet Nam',
    question: 'Ngay Quoc khanh cua nuoc Cong hoa Xa hoi Chu nghia Viet Nam la:',
    options: ['2/9', '30/4', '19/8', '22/12'],
    correctAnswer: 0,
    explanation: 'Ngay 2/9/1945, Chu tich Ho Chi Minh doc Tuyen ngon Doc lap tai Quang truong Ba Dinh, khai sinh nuoc VNDCCH.',
  },
  { subject: 'SU', difficulty: 2, chapter: 'Lich su Viet Nam',
    question: 'Hoi nghi Trung uong Dang (11/1939) co y nghia gi?',
    options: ['Chuyen huong chien luoc giai phong dan toc len hang dau', 'Mo dau chong Phap giai doan 2', 'Thanh lap Viet Minh', 'Khoi dau Cach mang Thang Tam'],
    correctAnswer: 0,
    explanation: 'Hoi nghi Trung uong Dang lan 6 (11/1939) quyet dinh dat nhiem vu giai phong dan toc len hang dau, tam thoi lui van de cach mang ruong dat, chuan bi luc luong.',
  },
  { subject: 'SU', difficulty: 2, chapter: 'Lich su the gioi',
    question: 'Ke hoach Marshall (1947-1952) cua My nham muc dich gi?',
    options: ['Phuc hoi kinh te Tay Au, ngan chan anh huong Lien Xo', 'Phat trien vu khi hat nhan', 'Xay dung khoi NATO', 'Vien tro Nhat Ban'],
    correctAnswer: 0,
    explanation: 'Ke hoach Marshall cung cap 13 ty USD de phuc hoi kinh te 17 nuoc Tay Au, giam thieu bat on va ngan chan su lan rong cua chu nghia cong san.',
  },
  { subject: 'SU', difficulty: 2, chapter: 'Lich su Viet Nam',
    question: 'Nguyen nhan sau xa cua cuoc khang chien chong My cuu nuoc la:',
    options: ['My muon bien mien Nam thanh thuoc dia kieu moi', 'Mau thuan ton giao', 'Tranh chap lanh tho', 'Can tranh bien gioi'],
    correctAnswer: 0,
    explanation: 'My can mien Nam Viet Nam lam can cu chong lai phe Xa hoi chu nghia, bien mien Nam thanh thuoc dia kieu moi — day la nguyen nhan sau xa.',
  },
  { subject: 'SU', difficulty: 2, chapter: 'Lich su the gioi',
    question: 'Phong trao Khong lien ket thanh lap nam 1961 de:',
    options: ['Giu doc lap, khong tham gia hai cuc My-Xo', 'Thanh lap NATO mo rong', 'Chong lai Trung Quoc', 'Hop tac kinh te Chau A'],
    correctAnswer: 0,
    explanation: 'Phong trao Khong lien ket (Non-Aligned Movement) tap hop cac nuoc moi gianh doc lap muon giu vai tro doc lap trong Chien tranh Lanh, khong phu thuoc My hay Lien Xo.',
  },
  { subject: 'SU', difficulty: 2, chapter: 'Lich su the gioi',
    question: 'Su kien "Buc tuong Berlin" sup do (11/1989) la bieu tuong cho:',
    options: ['Su ket thuc Chien tranh lanh o Chau Au', 'Thong nhat Chau Au', 'Nhat Ban troi day', 'Su suy yeu cua NATO'],
    correctAnswer: 0,
    explanation: 'Buc tuong Berlin sup do (11/11/1989) danh dau su ket thuc phan chia Dong-Tay Duc va la bieu tuong cua su sup do cua he thong xa hoi chu nghia Dong Au.',
  },
  { subject: 'SU', difficulty: 3, chapter: 'Lich su the gioi',
    question: 'Dac trung noi bat nhat cua trat tu the gioi "hai cuc" sau Chien tranh the gioi II la:',
    options: ['Su canh tranh gay gat giua My va Lien Xo, hai lien minh quan su doi dich', 'Hoa binh tuyet doi', 'Chau A that bai hoan toan', 'Cac nuoc nho yeu the'],
    correctAnswer: 0,
    explanation: 'Trat tu Yalta: the gioi bi chia thanh hai cuc voi My dung dau phe TBCN va Lien Xo dung dau phe XHCN, canh tranh quyen luc va vu trang an ninh.',
  },
  { subject: 'SU', difficulty: 3, chapter: 'Lich su Viet Nam',
    question: 'Dau vet de lai sau cuoc Khang chien chong My that su phuc tap vi:',
    options: ['Vi chien tranh keo dai, ta hai lon, nhung da tam muc giai phong dan toc', 'Vi My dau hang vo dieu kien', 'Vi Lien Xo truc tiep giup', 'Vi khong co ton that'],
    correctAnswer: 0,
    explanation: 'Cuoc khang chien hy sinh lon (>3 trieu nguoi), dat nuoc tan pha nang ne, nhung muc tieu giai phong dan toc va thong nhat dat nuoc da dat duoc (30/4/1975).',
  },
  { subject: 'SU', difficulty: 3, chapter: 'Lich su the gioi',
    question: 'Toan cau hoa kinh te hien nay mang lai thach thuc gi cho cac nuoc dang phat trien?',
    options: ['Khoang cach giau ngheo tang, phu thuoc kinh te vao cac nuoc lon', 'Mo rong thi truong rat de dang', 'Don gian hoa van hoa', 'Giam bat bien doi khi hau'],
    correctAnswer: 0,
    explanation: 'Toan cau hoa tao co hoi nhung cung dat ra thach thuc: khoang cach giau ngheo giua nuoc va trong nuoc tang; cac nuoc dang phat trien de bi phu thuoc kinh te, mat chu quyen chinh sach.',
  },
  { subject: 'SU', difficulty: 3, chapter: 'Lich su Viet Nam',
    question: 'Chinh sach "Doi moi" 1986 cua Dang ta co y nghia:',
    options: ['Chuyen doi sang kinh te thi truong dinh huong XHCN, mo ra giai doan phat trien moi', 'Lap lai kinh te tap the hoan toan', 'Ap dung mo hinh Xo Viet', 'Quoc huu hoa tu san'],
    correctAnswer: 0,
    explanation: 'Dai hoi VI (1986) phat dong Doi moi: chuyen doi tu kinh te ke hoach hoa tap trung sang nen kinh te thi truong dinh huong XHCN, mo cua hop tac quoc te, tao nen dong luc phat trien moi.',
  },
  { subject: 'SU', difficulty: 3, chapter: 'Lich su the gioi',
    question: 'Cach mang cong nghiep 4.0 (Industry 4.0) co dac trung chinh la:',
    options: ['Su hop nhat giua the gioi thuc-ao: AI, IoT, big data, robot tu dong', 'Phat trien may hoi nuoc', 'San xuat dai tra don gian', 'Nang luong hat nhan'],
    correctAnswer: 0,
    explanation: 'CMCN 4.0 la su ket hop giua the gioi vat ly, ky thuat so va sinh hoc: AI, IoT, big data, tu dong hoa, in 3D — tao nen bien doi co ban trong san xuat va xa hoi.',
  },

  // =========================================================================
  // DIA - Dia ly
  // =========================================================================

  { subject: 'DIA', difficulty: 1, chapter: 'Tu nhien',
    question: 'Viet Nam nam trong vu khi nao sau day?',
    options: ['Gio mua Chau A', 'Gio mua Chau Phi', 'Khi hau on doi', 'Khi hau dia trung hai'],
    correctAnswer: 0,
    explanation: 'Viet Nam nam trong vung gio mua Chau A, co khi hau nhiet doi gio mua am.',
  },
  { subject: 'DIA', difficulty: 1, chapter: 'Dan cu',
    question: 'Dan so Viet Nam hien nay xap xi:',
    options: ['~100 trieu nguoi', '~50 trieu nguoi', '~200 trieu nguoi', '~30 trieu nguoi'],
    correctAnswer: 0,
    explanation: 'Dan so Viet Nam nam 2023 xap xi 100 trieu nguoi, la 1 trong nhung nuoc dong dan nhat khu vuc.',
  },
  { subject: 'DIA', difficulty: 1, chapter: 'Tu nhien',
    question: 'Song dai nhat chay qua lanh tho Viet Nam la:',
    options: ['Song Mekong (Cuu Long)', 'Song Hong', 'Song Dong Nai', 'Song Da'],
    correctAnswer: 0,
    explanation: 'Song Mekong (Cuu Long) la song dai nhat Dong Nam A, chay qua mien Tay Nam Bo truoc khi do ra bien.',
  },
  { subject: 'DIA', difficulty: 1, chapter: 'Kinh te',
    question: 'Vung dong bang nao co dien tich lon nhat Viet Nam?',
    options: ['Dong bang song Cuu Long', 'Dong bang song Hong', 'Dong bang duyen hai mien Trung', 'Dong bang Bac Bo'],
    correctAnswer: 0,
    explanation: 'Dong bang song Cuu Long rong khoang 40.000 km², lon nhat ca nuoc, la vua lua cua Viet Nam.',
  },
  { subject: 'DIA', difficulty: 1, chapter: 'Tu nhien',
    question: 'Nui cao nhat Viet Nam la:',
    options: ['Fansipan', 'Pu Si Lung', 'Bach Ma', 'Ngoc Linh'],
    correctAnswer: 0,
    explanation: 'Fansipan (cao 3143m) o tinh Lao Cai la nui cao nhat Viet Nam, duoc menh danh "Noc nha Dong Duong".',
  },
  { subject: 'DIA', difficulty: 2, chapter: 'Tu nhien',
    question: 'Khi hau Viet Nam co tinh chat nhiet doi am gio mua vi:',
    options: ['Vi tri dia li giap bien Dong va tac dong cua gio mua', 'Nui cao che phu', 'Dong bang rong lon', 'Rung nhiet doi phu phe'],
    correctAnswer: 0,
    explanation: 'Vi tri giap bien Dong va tac dong cua cac hoat dong gio mua (Dong Bac, Tay Nam) quyet dinh khi hau nhiet doi am gio mua cua Viet Nam.',
  },
  { subject: 'DIA', difficulty: 2, chapter: 'Kinh te',
    question: 'Viet Nam la nuoc xuat khau lon nhat the gioi ve san pham nao?',
    options: ['Hat dieu', 'Gao', 'Ca phe', 'Cao su'],
    correctAnswer: 0,
    explanation: 'Viet Nam lien tuc la nuoc xuat khau hat dieu lon nhat the gioi, chiem hon 70% thi phan xuat khau toan cau.',
  },
  { subject: 'DIA', difficulty: 2, chapter: 'Dan cu',
    question: 'Qua trinh do thi hoa o Viet Nam dang dien ra nhanh chu yeu o:',
    options: ['Vung ven do cac thanh pho lon', 'Khu vuc mien nui', 'Dong bang song Hong truyen thong', 'Khu vuc bien dao'],
    correctAnswer: 0,
    explanation: 'Do thi hoa dien ra manh nhat o vung ven do TP.HCM, Ha Noi, Binh Duong do cong nghiep phat trien, thu hut lao dong dong.',
  },
  { subject: 'DIA', difficulty: 2, chapter: 'Tu nhien',
    question: 'Hien tuong El Nino thuong gay ra hau qua gi o mien Nam Viet Nam?',
    options: ['Han han, thieu nuoc nghiem trong', 'Bao lon', 'Lu lut nang ne', 'Lanh dot xuat'],
    correctAnswer: 0,
    explanation: 'El Nino gay ra tinh trang kho han o Chau A - Thai Binh Duong, dac biet la mien Nam Viet Nam bi han han keo dai, xam nhap man tang.',
  },
  { subject: 'DIA', difficulty: 2, chapter: 'Kinh te',
    question: 'Vung kinh te trong diem phia Nam cua Viet Nam bao gom:',
    options: ['TP.HCM, Binh Duong, Dong Nai, Ba Ria - Vung Tau', 'Ha Noi, Hai Phong, Quang Ninh', 'Da Nang, Quang Nam, Quang Ngai', 'Can Tho, Tien Giang, Long An'],
    correctAnswer: 0,
    explanation: 'Vung kinh te trong diem phia Nam gom 4 tinh: TP.HCM, Binh Duong, Dong Nai, Ba Ria - Vung Tau — dong gop ~40% GDP ca nuoc.',
  },
  { subject: 'DIA', difficulty: 3, chapter: 'Kinh te',
    question: 'Co cau kinh te chuyen dich theo huong "tang ty trong cong nghiep-dich vu, giam nong nghiep" phan anh xu the:',
    options: ['Cong nghiep hoa, hien dai hoa (CNH-HDH)', 'Nong nghiep hoa', 'Khai thac tai nguyen thien nhien', 'Xuat khau thu cong my nghe'],
    correctAnswer: 0,
    explanation: 'Su giam dan ty trong nong nghiep va tang ty trong cong nghiep, dich vu la dau hieu ro rang cua qua trinh CNH-HDH.',
  },
  { subject: 'DIA', difficulty: 3, chapter: 'Tu nhien',
    question: 'Viet Nam co uu the gi trong phat trien nang luong tai tao?',
    options: ['Duong bien dai, buc xa mat troi cao va gio phong phu', 'Nhieu khoan dau khi', 'Rung nhiet doi lon', 'Khoang san da dang'],
    correctAnswer: 0,
    explanation: 'Viet Nam co duong bien dai ~3260 km (wind/solar off-shore), buc xa mat troi lon o mien Nam (4-5 kWh/m²/ngay), gio bien manh — tao tiem nang vuot troi cho NLTT.',
  },
  { subject: 'DIA', difficulty: 3, chapter: 'Dan cu',
    question: 'Hau qua chinh cua tinh trang gia hoa dan so nhanh o Viet Nam la:',
    options: ['Tang ganh nang an sinh xa hoi, thieu lao dong tre', 'Tang truong kinh te nhanh', 'Giam ti le ngheo doi', 'Mo rong thi truong lao dong'],
    correctAnswer: 0,
    explanation: 'Gia hoa dan so tang ganh nang cho he thong luong huu, y te, an sinh xa hoi; trong khi ty le lao dong trong do tuoi giam dan tao ap luc cho phat trien kinh te.',
  },
  { subject: 'DIA', difficulty: 3, chapter: 'Kinh te',
    question: 'Lien ket vung kinh te o Viet Nam con nhieu bat cap vi:',
    options: ['Co che phan quyen chua dung, tinh canh tranh hon hon tac tu giua cac tinh', 'Khong co co so ha tang', 'Thieu von dau tu nuoc ngoai', 'Chuyen dich co cau qua nhanh'],
    correctAnswer: 0,
    explanation: 'Cac tinh co xu huong phat trien doc lap, canh tranh thu hut dau tu hon la phan cong hop tac, thieu co che dieu phoi vung hieu qua.',
  },
  { subject: 'DIA', difficulty: 3, chapter: 'Tu nhien',
    question: 'Bien doi khi hau va nuoc bien dang de doa nghiem trong nhat cho vung nao cua Viet Nam?',
    options: ['Dong bang song Cuu Long va vung bo bien thap', 'Tay Nguyen', 'Trung du mien nui Bac Bo', 'Mien Bac'],
    correctAnswer: 0,
    explanation: 'Dong bang song Cuu Long la noi thap nhat, de bi ngap lut khi nuoc bien dang; xam nhap man, mat dat san xuat la nguy co lon nhat trong boi canh BDKH.',
  },

  // =========================================================================
  // GDCD - Giao duc cong dan
  // =========================================================================

  { subject: 'GDCD', difficulty: 1, chapter: 'Phap luat',
    question: 'Do tuoi chiu trach nhiem hinh su day du o Viet Nam la:',
    options: ['Tu 18 tuoi tro len', 'Tu 14 tuoi tro len', 'Tu 16 tuoi tro len', 'Khong co gioi han'],
    correctAnswer: 0,
    explanation: 'Theo Bo luat Hinh su, nguoi tu du 18 tuoi chiu trach nhiem hinh su day du. Tu 14 tuoi chi chiu TNHS doi voi 1 so toi danh nghiem trong.',
  },
  { subject: 'GDCD', difficulty: 1, chapter: 'Dao duc',
    question: 'Pham chat dao duc nao duoc the hien khi ban giup do nguoi gap kho khan ma khong mong duoc dap?',
    options: ['Nhan ai, vi tha', 'Dung cam', 'Kien tri', 'Sang tao'],
    correctAnswer: 0,
    explanation: 'Giup do nguoi khac khong vi vu loi ca nhan the hien long nhan ai, vi tha — phm chat cao dep cua con nguoi.',
  },
  { subject: 'GDCD', difficulty: 1, chapter: 'Kinh te',
    question: 'Nen kinh te thi truong dinh huong XHCN tai Viet Nam co nghia la:',
    options: ['Kinh te thi truong co su quan ly cua Nha nuoc vi muc tieu cong bang xa hoi', 'Kinh te ke hoach hoa tap trung', 'Tu do kinh te tuyet doi', 'Kinh te quoc doanh chiem uu the tuyet doi'],
    correctAnswer: 0,
    explanation: 'Kinh te thi truong dinh huong XHCN: den co che thi truong (phan bo nguon luc hieu qua) nhung co su dieu tiet cua Nha nuoc nham dam bao cong bang, an sinh xa hoi.',
  },
  { subject: 'GDCD', difficulty: 1, chapter: 'Phap luat',
    question: 'Hien phap 2013 quy dinh quyen con nguoi o:',
    options: ['Chuong II', 'Chuong I', 'Chuong III', 'Chuong IV'],
    correctAnswer: 0,
    explanation: 'Hien phap 2013 quy dinh ve "Quyen con nguoi, quyen va nghia vu co ban cua cong dan" tai Chuong II (Dieu 14-49).',
  },
  { subject: 'GDCD', difficulty: 1, chapter: 'Chinh tri',
    question: 'Nguyen tac to chuc co ban cua Nha nuoc Viet Nam la:',
    options: ['Tap trung dan chu', 'Tam quyen phan lap', 'Phi tap trung hoa', 'Quyen luc chia deu'],
    correctAnswer: 0,
    explanation: 'Nha nuoc Viet Nam to chuc theo nguyen tac tap trung dan chu: tap trung quyen luc vao bo may trung uong nhung co su tham gia cua nhan dan.',
  },
  { subject: 'GDCD', difficulty: 2, chapter: 'Phap luat',
    question: 'Quoc hoi Viet Nam la co quan:',
    options: ['Quyen luc nha nuoc cao nhat, chuc nang lap phap', 'Hanh phap cao nhat', 'Tu phap cao nhat', 'Giam sat hien phap'],
    correctAnswer: 0,
    explanation: 'Quoc hoi la co quan dai bieu cao nhat cua nhan dan, quyen luc nha nuoc cao nhat. Quoc hoi thuc hien quyen lap hien, lap phap, giam sat toi cao.',
  },
  { subject: 'GDCD', difficulty: 2, chapter: 'Kinh te',
    question: 'Lam phat la hien tuong:',
    options: ['Gia ca tang lien tuc tren dien rong, suc mua dong tien giam', 'Tang truong kinh te manh me', 'Giam gia hang hoa', 'Tang ty gia hoi doai'],
    correctAnswer: 0,
    explanation: 'Lam phat la su tang lien tuc cua muc gia ca chung, dan den giam suc mua cua tien te.',
  },
  { subject: 'GDCD', difficulty: 2, chapter: 'Phap luat',
    question: 'Hanh vi nao sau day vi pham quyen so huu tri tue?',
    options: ['Sao chep sach ma khong xin phep tac gia', 'Doc sach trong thu vien', 'Mua sach ban quyen', 'Trich dan co chi nguon'],
    correctAnswer: 0,
    explanation: 'Sao chep tac pham ma khong xin phep tac gia/nha xuat ban la vi pham quyen tac gia theo Luat So huu tri tue.',
  },
  { subject: 'GDCD', difficulty: 2, chapter: 'Dao duc',
    question: 'Van de gi khi giai quyet mau thuan giua nghia vu gia dinh va nghia vu xa hoi?',
    options: ['Can hoa giai, ket hop hai nghia vu mot cach linh hoat', 'Chi uu tien gia dinh', 'Chi uu tien xa hoi', 'Tranh manh thu nao de theo that'],
    correctAnswer: 0,
    explanation: 'Can hoa giai, ket hop hai nghia vu: giu hoan tro gia dinh la nen tang, dong thoi thuc hien tot nghia vu voi xa hoi — day la su linh hoat trong xu ly mau thuan phat sinh.',
  },
  { subject: 'GDCD', difficulty: 2, chapter: 'Chinh tri',
    question: 'Su lanh dao cua Dang Cong san Viet Nam duoc quy dinh ro nhat o:',
    options: ['Dieu 4 Hien phap 2013', 'Luat to chuc Quoc hoi', 'Nghi dinh Chinh phu', 'Luat thanh nien'],
    correctAnswer: 0,
    explanation: 'Dieu 4 Hien phap 2013 quy dinh: "Dang Cong san Viet Nam ... la luc luong lanh dao Nha nuoc va xa hoi."',
  },
  { subject: 'GDCD', difficulty: 3, chapter: 'Phap luat',
    question: 'Nha nuoc phap quyen xa hoi chu nghia co dac trung co ban la:',
    options: ['Phap luat toi cao, quyen con nguoi duoc dam bao, Nha nuoc chiu su giam sat', 'Quyen hanh phap noi tren luat phap', 'Tu phap khong doc lap', 'Quoc hoi khong co quyen giam sat'],
    correctAnswer: 0,
    explanation: 'Nha nuoc phap quyen: hien phap va phap luat co gia tri cao nhat; quyen con nguoi duoc bao dam; co phan cong, phoi hop, kiem soat giua cac quyen nha nuoc.',
  },
  { subject: 'GDCD', difficulty: 3, chapter: 'Kinh te',
    question: 'Toan cau hoa kinh te de lai thach thuc gi doi voi chu quyen quoc gia?',
    options: ['Ap luc canh tranh buoc phai mo cua, kho bao ho kinh te trong nuoc', 'Tang khung hoang gia tieu dung', 'Giam FDI', 'Tang chu nghia bao ho'],
    correctAnswer: 0,
    explanation: 'Toan cau hoa tao ap luc phai mo cua thi truong, ha rao can thuong mai — giam kha nang bao ho cac nganh trong nuoc, de bi anh huong boi khung hoang ben ngoai.',
  },
  { subject: 'GDCD', difficulty: 3, chapter: 'Chinh tri',
    question: 'Y nghia cua nguyen tac "tat ca quyen luc nha nuoc thuoc ve nhan dan" trong Hien phap Viet Nam?',
    options: ['Nhan dan la chu the quyen luc, thuc hien thong qua Quoc hoi va cac co quan dai dien', 'Nhan dan truc tiep quan ly dat nuoc hang ngay', 'Quan doi co quyen quyet dinh', 'Dang lanh dao truc tiep nen tuong tu'],
    correctAnswer: 0,
    explanation: 'Nguyen tac nay khang dinh chu quyen nhan dan — nhan dan uy quyen cho co quan nha nuoc (Quoc hoi, HDND), khong truc tiep thi hanh quyen luc ma thong qua dai dien.',
  },
  { subject: 'GDCD', difficulty: 3, chapter: 'Dao duc',
    question: 'Tac dong cua cach mang cong nghiep 4.0 doi voi dao duc nghe nghiep:',
    options: ['Yeu cau nang cao liem chinh, trach nhiem trong xu ly du lieu ca nhan, AI', 'Loai bo hoan toan dao duc nghe nghiep', 'Giam tam quan trong cua dao duc', 'Chi anh huong den linh vuc cong nghe'],
    correctAnswer: 0,
    explanation: 'CMCN 4.0 dat ra nhung van de dao duc nghe nghiep moi: bao mat du lieu, su dung AI co trach nhiem, canh tranh cong bang — doi hoi nang cao liem chinh va trach nhiem.',
  },
  { subject: 'GDCD', difficulty: 3, chapter: 'Phap luat',
    question: 'Tinh that quyen cua phap luat Viet Nam the hien qua:',
    options: ['Phap luat bat buoc moi nguoi tuan theo, Nha nuoc bao dam bang cung che', 'Chi ap dung cho nguoi dan thuong', 'Chi can thuc hien khi thay can thiet', 'Tu nguyen thuc hien tuy y'],
    correctAnswer: 0,
    explanation: 'Tinh bat buoc chung (that quyen): phap luat ap dung chung cho moi doi tuong trong xa hoi, ai vi pham deu bi xu ly bang suc manh cua Nha nuoc.',
  },
];

async function main() {
  console.log('Bat dau seed du lieu cau hoi...');
  console.log(`Tong so cau hoi se them: ${questions.length}`);

  // Xoa cau hoi cu neu co (chi trong moi truong dev)
  if (process.env.NODE_ENV !== 'production') {
    const deleted = await prisma.question.deleteMany({});
    console.log(`Da xoa ${deleted.count} cau hoi cu.`);
  }

  // Insert theo batch 50 de tranh qua tai
  const batchSize = 50;
  let inserted = 0;
  for (let i = 0; i < questions.length; i += batchSize) {
    const batch = questions.slice(i, i + batchSize);
    await prisma.question.createMany({ data: batch });
    inserted += batch.length;
    console.log(`  Da them ${inserted}/${questions.length} cau hoi...`);
  }

  // Thong ke
  const counts = await prisma.question.groupBy({
    by: ['subject', 'difficulty'],
    _count: { id: true },
    orderBy: [{ subject: 'asc' }, { difficulty: 'asc' }],
  });

  console.log('\nTong ket seed:');
  for (const c of counts) {
    console.log(`  ${c.subject} | Do kho ${c.difficulty}: ${c._count.id} cau`);
  }

  console.log('\nSeed hoan tat!');
}

main()
  .catch((e) => {
    console.error('Loi seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
